### ISSUE TITLE
Is this project discontinued?

### ISSUE THREAD

**Issue by lu-zero** [exaroth/subrosa#5]
Looks impressive in many ways and would be a pity.

**Comment by exaroth** [comment]
Hello, in the past months I haven't had much time to work on this project, major goal for me when developing Subrosa was to learn principles of creating web applications in Flask/Python and this goal was achieved, I'm considering this project to be more of an educational app for people that want to learn Flask and see some working code rather than replacement for existing CMS apps out there. If people find bugs/problems with it I'm happy to merge any pull requests, apart from that further development of Subrosa has been stopped.

**Comment by lu-zero** [comment]
I couldn't find better Flask-based blogs with this featureset so I was wondering =)
